scr_enable_screen_border(1);
scr_enemy_object_init();
recruitcount = 5;
talkmax = 90;
image_speed = 0;
idlesprite = spr_tenna_point_up;
hurtsprite = spr_tenna_hurt;
sparedsprite = spr_tenna_sad;
custom_draw_example = 1;
darken = 0;
darkenalpha = 0;
myattackchoice = 0;
haveusedultimate = 0;
siner = 0;
turn = 0;
phaseturn = 0;
phase = 1;
phaseturn = 0;
endcon = 0;
endtimer = 0;
end_cutscene_version = 0;
balloonorder = 0;
ballooncon = 0;
balloonend = 1;
minigamedialogue = 0;
doubleminigamedialogue = 0;
smashcutdialgue = 0;
rimshotdialogue = 0;
dialogueorder = 0;
talkedcon = 0;
ralseitalks = 0;
susietalks = 0;
debugvar = 0;
attackchosen = false;
minigametype = "susiezilla";
difficulty = 0;
minigametype2 = "none";
difficulty2 = 0;
minigametype3 = "none";
difficulty3 = 0;
randomchosenprev1 = -1;
randomchosenprev2 = -1;
intro = 0;
introtimer = 0;
points = 0;
gothit = false;
bet = false;
betamount = 0;
pointsmultiplier = 1;
pointsmultiplierthisturn = 4;
haveusedbetbefore = false;
extrapointsviatension = 0;
popularboy = false;
saveralseihp = 0;
ralseihpprev = 0;
healthphase = 1;
resetralsei = false;
didkrisdoswordroute = false;
ralseiplushmarker = instance_create(-1000, -1000, obj_marker);
ralseiplushmarker.sprite_index = spr_gameshow_drowningRalsei_ralsei_origin_edit;
lancermarker = instance_create(-1000, -1000, obj_marker);
lancermarker.sprite_index = spr_lancer_lt_stool;
lancermarker.image_xscale = 2;
lancermarker.image_yscale = 2;
lancerspin = false;
lancerindex = 0;
lancercheat = false;
lancercheatpoints = 0;
ballvar = 0;
insanitycowboycount = 0;
insanitychefcount = 0;
if (global.flag[1050] == 1)
{
    didkrisdoswordroute = true;
}
minigametransition_con = 0;
minigametransition_timer = 0;
minigametransition_speed = 0;
minigametransition_variant = 0;
tenna_actor = instance_create(camerax() + 526, cameray() + 260, obj_actor_tenna);
tenna_actor.preset = 2;
audience_goes_away = false;
keep_em_alive = false;
scr_speaker("tenna");
global.fc = 22;
global.typer = 80;
if (!i_ex(obj_tenna_enemy_bg))
{
    instance_create(camerax(), cameray(), obj_tenna_enemy_bg);
}
instance_create(x, y, obj_tenna_minigame_ui);
with (obj_battleback)
{
    instance_destroy();
}
minigamefailcount = 0;
minigamefailcountprev = 0;
minigamefailcon = 0;
minigamefailtimer = 0;
minigamefailtimer2 = 0;
totalfails = 0;
deletefacebug = false;
target = 0;
damage = 0;
element = 0;
extravar = 0;
stopshoot = 0;
cowboy1tooknodamage = false;
alreadydidgianttenna = false;
alreadydidsharpshoot = false;
completedrhythmwithouttakingdamage = 0;
completedrhythmwithouttakingdamage2 = 0;
completedchefwithouttakingdamage = 0;
umbrellawithouttakingdamage = 0;
ralsei1withouttakingdamage = 0;
ralsei2withouttakingdamage = 0;
smashcutwithouttakingdamage = 0;
minigamecount = 0;
minigameactivated = false;
strng = "";
testlightemup = false;
testsharpshoot = false;
spotlightcount = 0;
extrapoints = 0;
staticfadetimer = 30;
staticfadetimermax = 300;
staticfadecon = 0;
minigameinsanity = 0;
minigameinsanitycount = 0;
minigameinsanitydamage = false;
finalattackminigameswitch = 0;
finalattackminigametimer = 0;
finalttackminigametype = 0;
finalattackminigamedifficulty = 0;
rhythm_combo[0] = 0;
rhythm_combo[1] = 0;
rhythm_combo[2] = 0;
